### ISSUE TITLE
Would like to leverage these actions for a private repo?

### ISSUE THREAD

**Issue by acampbel** [zaikun/gitpersonal#1]
Hi @zaikunzhang , 

This is an interesting repo and I am glad you have been able to make good use of the MATLAB Actions. Would you prefer to use this for a different/private repository? The way you are doing this here is perfectly fine, but it might be easier if you really want to point to a private repository. If this is something you are interested in, feel free to send an email to continuous-integration@mathworks.com to talk through options you may have to do so.

Thanks!
Andy

**Comment by zaikunzhang** [comment]
Thanks for your comment. Thank MathWorks and GitHub for making MATLAB CI possible. 

This is a project under development and not ready for being public. So it would be perfect if I could turn this repo private. However, for private repos, GitHub imposes tons of limitations on the usage of GitHub Actions, and payments may be necessary. So I cannot. Thanks.
